### ISSUE TITLE
Making changes to subnet CIDR ranges

### ISSUE THREAD

**Issue by tomweston** [unifio/terraform-aws-vpc#26]
Im trying to modify the  following section in examples/complete/main.tf to break the generated subnets into /22's 

Can you provide some guidance as to what is being computed here? 

```
dmz_cidrs = ["${cidrsubnet(var.vpc_cidr,3,0)}",
    "${cidrsubnet(var.vpc_cidr,3,1)}",
    "${cidrsubnet(var.vpc_cidr,3,2)}",
    "${cidrsubnet(var.vpc_cidr,3,3)}",
  ]

  lan_cidrs = ["${cidrsubnet(var.vpc_cidr,4,8)}",
    "${cidrsubnet(var.vpc_cidr,4,9)}",
    "${cidrsubnet(var.vpc_cidr,4,10)}",
    "${cidrsubnet(var.vpc_cidr,4,11)}",
    "${cidrsubnet(var.vpc_cidr,4,12)}",
    "${cidrsubnet(var.vpc_cidr,4,13)}",
    "${cidrsubnet(var.vpc_cidr,4,14)}",
    "${cidrsubnet(var.vpc_cidr,4,15)}",
  ]
```

Or is is subnet range defined in the following section:

```
resource "aws_subnet" "lan" {
  count = "${(length(var.azs_provisioned_override) > 0 && var.azs_provisioned_override[0] != "non_empty_list" ? length(var.azs_provisioned_override) : var.azs_provisioned) * (length(var.lans_per_az) > 0 ? var.lans_per_az : "1")}"

  availability_zone = "${length(var.azs_provisioned_override) > 0 && var.azs_provisioned_override[0] != "non_empty_list" ? "${data.aws_region.current.name}${element(var.azs_provisioned_override,count.index)}" : element(data.aws_availability_zones.available.names,count.index)}"
  cidr_block        = "${length(var.lan_cidrs) > 0 && var.lan_cidrs[0] != "non_empty_list" ? element(var.lan_cidrs,count.index) : cidrsubnet(data.aws_vpc.base.cidr_block,lookup(var.az_cidrsubnet_newbits, (length(var.azs_provisioned_override) > 0 && var.azs_provisioned_override[0] != "non_empty_list" ? length(var.azs_provisioned_override) : var.azs_provisioned) * (length(var.lans_per_az) > 0 ? var.lans_per_az : "1")),count.index + (lookup(var.az_cidrsubnet_offset, length(var.azs_provisioned_override) > 0 && var.azs_provisioned_override[0] != "non_empty_list" ? length(var.azs_provisioned_override) : var.azs_provisioned) * (length(var.lans_per_az) > 0 ? var.lans_per_az : "1")))}"
  vpc_id            = "${var.vpc_id}"

  tags {
    application = "${var.stack_item_fullname}"
    managed_by  = "terraform"
    Name        = "sn-lan-${count.index}-${var.stack_item_label}"
  }
}
```

Thanks for your help.. :)
Great work by the way!

**Comment by blakeneyops** [comment]
The module is designed to function with very few inputs. The default behavior for the `az` module is to take the VPC CIDR and break it into 2 public and 2 private subnets across 2 availability zones. In that scenario it is adding 2 bits to the subnet ranges, so a /20 VPC CIDR would yield the result you are looking for under those conditions without specifying anything for `dmz_cirs` and `lan_cidrs`. You can adjust the number of AZs and the number of private subnets per AZ with the `azs_provisioned` and `lans_per_az` parameters.

The reason that formulation is so thick is because you can override most parameters to meet your needs, which is what the `complete` example is showing. You could feed raw CIDR strings in there if that is your preference, but be be aware it isn't going to sanity check against other parameters like your VPC CIDR until execution time.

So, the default behavior could also be specified as follows:

```
dmz_cidrs = ["${cidrsubnet(var.vpc_cidr,2,0)}",
  "${cidrsubnet(var.vpc_cidr,2,1)}"
  ]

lan_cidrs = ["${cidrsubnet(var.vpc_cidr,2,2)}",
  "${cidrsubnet(var.vpc_cidr,2,3)}",
]
``` 

OR

```
dmz_cidrs = ["172.16.0.0/22",
  "172.16.4.0/22"
  ]

lan_cidrs = ["172.16.8.0/22",
  "172.16.12.0/22",
]
``` 

Let me know if this answers your question. Thanks!

**Comment by tomweston** [comment]
Awesome.. 

Makes sense now.

Thanks!

**Comment by blakeneyops** [comment]
Great, let me know if I can help with anything else. PRs are welcome if you have any thoughts on improvements to the code, examples or docs. Thanks.
